return {
    {{"Legitbot"}, {"Ragebot"}, {"Visuals"}, {"Misc"}, {"Settings"}},
    {{"Master Switch"}, {"Master Switch"}, {"Master Switch"}, {"Master Switch"}},
    {
        {"Aimbot"},
        {"Triggerbot"},
        {"Weapon"},
        {"Other"},
        {"Semirage"},
        {"Aimbot"},
        {"Accuracy"},
        {"Hitscan"},
        {"Anti-Aim"},
        {"Overlay"},
        {"Local"},
        {"World"},
        {"Chams"},
        {"Skins"},
        {"Other"},
        {"General"},
        {"Movement"},
        {"Enhancement"},
        {"Configurations"},
        {"Lua Scripts"},
        {"Theme"},
        {"Advanced"}
    },
    {
        {"Toggle"},
        {"Weapon"},
        {"Hitbox Selection"},
        {"Toggle"},
        {"Weapon"},
        {"Hitbox Scan"},
        {"Aiming"},
        {"Visibility"},
        {"Accuracy"},
        {"Target"},
        {"Movement"},
        {"Extra"},
        {"Aimbot"},
        {"Position Adjustment"},
        {"Anti-Aim"},
        {"Toggle"},
        {"Automation"},
        {"Target"},
        {"Extra"},
        {"Weapon"},
        {"Position Adjustment"},
        {"Weapon Movement"},
        {"Movement"},
        {"Hitbox Points"},
        {"Advanced"},
        {"Mode"},
        {"Performance"},
        {"Base Direction"},
        {"Left Direction"},
        {"Right Direction"},
        {"Extra"},
        {"Condition"},
        {"Advanced"},
        {"Friendly"},
        {"Enemy"},
        {"Weapon"},
        {"Camera"},
        {"Helper"},
        {"Extra"},
        {"Materials"},
        {"Nade"},
        {"Selection"},
        {"Model"},
        {"Attachments"},
        {"Ragdoll"},
        {"Backtrack"},
        {"Model"},
        {"Attachments"},
        {"Ragdoll"},
        {"Model"},
        {"Viewmodel Weapon"},
        {"Viewmodel Arms"},
        {"Attachments"},
        {"Ghost"},
        {"Weapon"},
        {"Nades"},
        {"Enabled"},
        {"Preview"},
        {"List"},
        {"Configuration"},
        {"Stickers"},
        {"Extra"},
        {"Effects"},
        {"Performance"},
        {"Restrictions"},
        {"Bypass"},
        {"Server"},
        {"Extra"},
        {"Logs"},
        {"Jump"},
        {"Other"},
        {"Autothrow"},
        {"Strafe"},
        {"Speed Burst"},
        {"Fakelag"},
        {"Fakelatency"},
        {"Appearance"},
        {"Manage configurations"},
        {"Manage scripts"},
        {"Window Header"},
        {"Navigation"},
        {"Window Footer"},
        {"UI"},
        {"Tab List"},
        {"Manage advanced settings"}
    },
    {
        {"Enable", "Enables legit aimbot."},
        {"Aim Key", "Set the aimbot on key."},
        {"Toggle Key", "Set the toggle key to enable/disable aimbot."},
        {"Auto Fire", "Fires without pressing any key."},
        {"Fire On Press", "Fires when pressing the aimbot key."},
        {"Auto Pistol Interval", "Interval between shots for automatic mode."},
        {"Enable", "Enables triggerbot."},
        {"Trigger Key", "Activate trlggerbot on key press."},
        {"Auto Fire", "Let triggerbot fire without pressing any key."},
        {"Walk Speed Customization", "Enable walk speed modifications."},
        {"Walk Speed", "Modify walk speed with this amount."},
        {"Quick Stop", "Makes you stop faster by counter strafing."},
        {"Backtrack Time", "How many positions in the past are allowed."},
        {"Knife Triggerbot", "Enable knife triggerbot."},
        {"Silent Aimbot", "Autoaim when in Low FOV range."},
        {"Auto Stop", "Stop when aimbot fires to lower inaccuracy."},
        {"Backtracking", "Aim at enemy history positions."},
        {"Resolver", "lmprove accuracy when shooting at enemy anti-aim."},
        {"Type", "Maximum affects visible animation."},
        {"Direction", {"Auto", "Manual", "Choose mode for selecting direction."}},
        {"Left Side"},
        {"Right Side"},
        {"On Enemy Aiming", "Activate anti-aim only when enemy is aiming at you."},
        {"Disable On Knife", "Disable anti-aim when holding knife."},
        {"Disable On Grenade", "Disable anti-aim when holding a grenade."},
        {"Enable", "Enables rage aimbot."},
        {"Auto Pistol", "Makes pistol fire like an automatic weapon."},
        {"Auto Revolver", "Auto cocks the revolver for quicker fire."},
        {"Auto Scope", {"Off", "On - Auto Unzoom", "On - No Unzoom", "Scopes with sniper automatically when firing."}},
        {"FOV", "Maximum field of view the aimbot will target within."},
        {"Aim Lock", "lncrease priority of latest target."},
        {"Silent Aim", "Suppress view movement when aimbotting."},
        {"Knifebot", "Automatically knife when your target is in range."},
        {"Backtracking", "Aim at enemy history positions."},
        {"Resolver", "lmprove accuracy when shooting at enemy anti-aim."},
        {"Slow Walk Key", "Slow down player movement while holding this key."},
        {"Slow Walk Speed", "Scale movement speed by this value."},
        {"Quick Stop", "Makes you stop faster by counter strafing."},
        {"Auto Peek Enable"},
        {"Auto Peek Key"},
        {"Auto Peek Indicator"},
        {"Auto Peek Type", {"Hold", "Toggle", ""}},
        {"Auto Peek Maintain Oringin", "Keep origin between shots when holding auto peek."},
        {"Max Processing Time", "Lower this value to maintain better FPS."},
        {"Fake Duck", "Allows you to shoot higher while crouching."},
        {"Fake Duck Style", {"Duck", "Unduck", ""}},
        {"Static Legs", "Makes your legs static when slow walking."},
        {"Disable Conditions"},
        {"Shift On Shot", "Prevent your on shot model from getting hit."},
        {"Anti-Align Type", {"Lowerbody", "Micromovement", ""}},
        {"Auto Direction", "Set anti-aim based on enemy position."},
        {"Auto Direction Priority", {"FOV Based", "Distance Based", ""}},
        {"Anti-Resolver", "Makes continous shots harder to hit."},
        {"Pitch Angle", {"Off", "89°", "180° (Untrusted)", ""}},
        {"Fake Expose Toggle", "Flick fake head on edge when enabled."},
        {"Fake Expose Type", {"1s", "1.5s", "Method of fake expose."}},
        {"Box", {"Off", "Outlined", "Normal", "Draw 2D box around entity."}},
        {"Box Precision", "Match 2D box with model bounds."},
        {"Name", "Draw entity name."},
        {"Skeleton", "Draw player skeleton."},
        {"Health", "Configure health options."},
        {"Armor", "lndicate helmet and kevlar."},
        {"Weapon", {"Off", "Icon", "Name", "Draw weapon of player."}},
        {"Weapon Filter", {"Active", "Active + Nades", "All", ""}},
        {"Ammo", "Amount of ammo left in weapon."},
        {"Flags", "Show player activity."},
        {"Money", "Draw amount of money player has."},
        {"Barrel", "Draw lines where players is looking."},
        {"Dormant", "Show dormant players."},
        {"Box", {"Off", "Outlined", "Normal", "Draw 2D box around entity."}},
        {"Box Precision", "Match 2D box with model bounds."},
        {"Name", "Draw entity name."},
        {"Skeleton", "Draw player skeleton."},
        {"Health", "Configure health options."},
        {"Armor", "lndicate helmet and kevlar."},
        {"Weapon", {"Off", "Icon", "Name", "Draw weapon of player."}},
        {"Weapon Filter", {"Active", "Active + Nades", "All", ""}},
        {"Ammo", "Amount of ammo left in weapon."},
        {"Flags", "Show player activity."},
        {"Money", "Draw amount of money player has."},
        {"Barrel", "Draw lines where players is looking."},
        {"Dormant", "Show dormant players."},
        {"Box", {"Off", "Outlined", "Normal", "Draw 2D box around entity."}},
        {"Name", {"Off", "Icon", "Name", "Draw entity name."}},
        {"Ammo", "Amount of ammo left in weapon."},
        {"Nades", "Draw thrown nades."},
        {"Defuser", "Display defusers when missing one."},
        {"C4 Timer", "Display time till C4 explosion."},
        {"Danger Zone Items", "Various items from danger zone."},
        {"Danger Zone Turret", "Turret from danger zone."},
        {"Third Person Enable", "Enable third person view."},
        {"Third Person Distance", "Distance of the camera."},
        {"View FOV", "Override the game field of view."},
        {"Viewmodel FOV", "Override the model field of view."},
        {"Smooth Ghost Model", "Match fake ghost model position with real."},
        {"Wallbang Info", "Show penetrable space on walls."},
        {"Out Of View", {"Off", "Arrow", "Arrow + Info", "Display out of view enemies indicator."}},
        {"Out Of View Scale", "Scale the positioning of indicators from screen center."},
        {"Hit Effects", "Effects when hitting an enemy."},
        {"Damage Indicator"},
        {"Bullet Tracers Mode", {"Off", "Latest", "All", "Visualize bullet paths."}},
        {"Bullet Tracers Filter"},
        {"Sounds", "Display audible sounds on screen."},
        {"Walls Color"},
        {"Static Props Color"},
        {"Skybox", "Change how the sky looks."},
        {"Inferno", "Draw molotov covered inferno."},
        {"Grenade Tracer", "Visualize predicted grenade trajectory."},
        {"Grenade Warning", "Show predicted explosion warning."},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Health", "Glow effect on model."}},
        {"Occluded", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Material occluded by walls."}},
        {"Visible", {"Off", "Flat", "Color", "Metallic", "Glow", "Pearescent", "Bubble", "Textured", "Invisible", "Visible material."}},
        {"Overlay", {"Off", "Wireframe", "Apply over previous materials."}},
        {"Glow", {"Off", "Color", "Glow effect on model."}},
        {"Add"},
        {"Remove"},
        {"Item", "Select weapon or model."},
        {"Paint Kits", "Select skin of model."},
        {"Wear", "Quality of item texture."},
        {"Seed", "Seed of texture generation."},
        {"StatTrak", "kill counter of weapon."},
        {"Name", "Custom name of item."},
        {"A"},
        {"B"},
        {"C"},
        {"D"},
        {"E"},
        {"Radar", "Display custom radar."},
        {"Radar Range", "Set radar range."},
        {"Radar Transparency", "Set radar transpareny."},
        {"Crosshair", "Display custom crosshair."},
        {"Crosshair Recoil", {"Off", "Line", "Fade", "Draws the spot where your shots will go."}},
        {"Anti-OBS", "Hide visuals from screen recorder."},
        {"Anti-Screenshot", "Hide visuals from screenshots."},
        {"Preserve Killfeed", "Preserve the killfeed."},
        {"Shared ESP", {"Off", "Shared with Team", "Shared with All", "Share ESP information to other players."}},
        {"Effects Removal", "Disable selected effects."},
        {"Performance Options", "Various options to improve game performance."},
        {"Anti-Untrusted", "Restrict various features on Valve servers."},
        {"Bypass sv_pure", "Allow custom models and materials from csgo directory."},
        {"Bypass sv_cheats", "Bypass protected convars."},
        {"Unlock Steam Achievements"},
        {"Show hidden ConVars"},
        {"sv_maxunlag", "Configure server-side max backtracking factor."},
        {"sv_maxusrcmdprocessticks", "Configure server-side max lag factor."},
        {"Player List", "Configure per player settings."},
        {"Show Spectators", "See who is spectating you."},
        {"Show Ranks", "Show rank of plavers."},
        {"Auto-Accept Match", "Automatically Accept match."},
        {"Overwatch Revealer", "Show player information in Overwatch demo."},
        {"Log Damage", "Log damage dealt to enemies."},
        {"Log Purchases", "Log purchases made by enemy team."},
        {"Log Console", "Log console messages on screen."},
        {"Log Misses", "Print information about last target shot miss."},
        {"Auto Jump", {"Off", "Perfect", "Legit", "Select auto jump mode for bunnyhopping."}},
        {"Edge Jump", "Jump right before falling of an edge."},
        {"Duck Jump", "Reach higher by crouching while jumping."},
        {"Auto Jump-Bug", "No fall damage when landing from certain height."},
        {"Fast Duck", "Exploit movement code to crouch quicker."},
        {"Slide Walk", "Glitch animation to appear as sliding."},
        {"Enable", "Automatically throw grenades/incendiary."},
        {"Grenade Distance", "Distance from the target to autothrow the grenade."},
        {"Incendiary Distance", "Distance from the target to autothrow the incendiary."},
        {"Enable", "Enable autostrafer to gain more speed."},
        {"Air Strafe", "lncreases forward speed while jumping."},
        {"Strafe Mode", {"Silent", "Normal", "Sideways", "W-Only", "Mouse", "Select style of autostrafing."}},
        {"Circle Strafe", "Strafe in circles when pressing a key."},
        {"Snake Strafe", "Strafe like a snake when pressing a key."},
        {"Retrack Speed", "Autostrafe in direction of pressed movement keys."},
        {"WASD-Movement", "Autostrafe in direction of pressed movement keys."},
        {"Enable", "Enable the speed"},
        {"Key", "Key to activate the speed"},
        {"Indicator", "Show indicator"},
        {"Enable", "Enable lag effect."},
        {"On Key", "Enable lag only when holding this key."},
        {"Type", {"Normal", "Adaptive", "Random", "Switch", 'Type or "pattern" of lag'}},
        {"Factor", "How many commands will be choked."},
        {"Conditions", "Configure fakelag options."},
        {"Enable", "Enable latency modifier."},
        {"On Key", "lncrease latency only when holding this key."},
        {"Amount", "Absolute latency to achieve."},
        {"Steal Name", "Steal other player name, limited to 5 times."},
        {"Invisible Name", "Make your name invisible."},
        {"Chat Spam", "Advertise AIMWARE in chat."},
        {"Clantag Changer", "Set AIMWARE.net as your clantag."},
        {"Name", "Create or rename configuration"},
        {"Create"},
        {"Rename"},
        {"Load"},
        {"Save"},
        {"Reset"},
        {"Delete"},
        {"Export To Clipboard"},
        {"Import From Clipboard"},
        {"Set As Default"},
        {"Refresh List"},
        {"Name", "Create or rename script"},
        {"Create"},
        {"Rename"},
        {"Edit (BETA)"},
        {"Load"},
        {"Unload"},
        {"Reset Lua State"},
        {"Delete"},
        {"Set As Autorun"},
        {"Refresh List"},
        {"Background"},
        {"Line"},
        {"Text"},
        {"Background"},
        {"Active"},
        {"Active Shadow"},
        {"Text"},
        {"Background"},
        {"Text"},
        {"Background #1"},
        {"Background #2"},
        {"Border"},
        {"Text"},
        {"Text Active"},
        {"Active Shadow"},
        {"Tab Active Decorator"},
        {"Tab Active Background"},
        {"Open Menu Key", "Bind for main menu toggle."},
        {"Open Console Key", "Console for more customization."},
        {"Dpi Scale", {"75%", "100% (default)", "125%", "150%", "175&", "200%", "225%", "250%", "275%", "300%", "Scale the UI size by this amount."}},
        {"Open Settings Folder"},
        {"Language", "Set the language of the menu."}
    },
    {
        {"Hitbox Advance Multiplier", "How fast aimbot should switch to the next hitbox."},
        {"Nearest To Crosshair", "Priority hitbox nearest to crosshair as first."},
        {"Hitbox Advance Multiplier", "How fast aimbot should switch to the next hitbox."},
        {"Nearest To Crosshair", "Priority hitbox nearest to crosshair as first."},
        {"Hitbox Advance Multiplier", "How fast aimbot should switch to the next hitbox."},
        {"Nearest To Crosshair", "Priority hitbox nearest to crosshair as first."},
        {"Hitbox Advance Multiplier", "How fast aimbot should switch to the next hitbox."},
        {"Nearest To Crosshair", "Priority hitbox nearest to crosshair as first."},
        {"Hitbox Advance Multiplier", "How fast aimbot should switch to the next hitbox."},
        {"Nearest To Crosshair", "Priority hitbox nearest to crosshair as first."},
        {"Hitbox Advance Multiplier", "How fast aimbot should switch to the next hitbox."},
        {"Nearest To Crosshair", "Priority hitbox nearest to crosshair as first."},
        {"Hitbox Advance Multiplier", "How fast aimbot should switch to the next hitbox."},
        {"Nearest To Crosshair", "Priority hitbox nearest to crosshair as first."},
        {"Hitbox Advance Multiplier", "How fast aimbot should switch to the next hitbox."},
        {"Nearest To Crosshair", "Priority hitbox nearest to crosshair as first."},
        {"Hitbox Advance Multiplier", "How fast aimbot should switch to the next hitbox."},
        {"Nearest To Crosshair", "Priority hitbox nearest to crosshair as first."},
        {"Hitbox Advance Multiplier", "How fast aimbot should switch to the next hitbox."},
        {"Nearest To Crosshair", "Priority hitbox nearest to crosshair as first."},
        {"Hitbox Advance Multiplier", "How fast aimbot should switch to the next hitbox."},
        {"Nearest To Crosshair", "Priority hitbox nearest to crosshair as first."},
        {"Trigger Delay", "Delay shot after trigger lock."},
        {"Trigger Burst", "Keep firing after trigger lock."},
        {"Hit Chance", "Minimum chance to hit before triggerbot shoots."},
        {"Anti-Recoil", "Account for recoil when trigger scanning."},
        {"Trigger Delay", "Delay shot after trigger lock."},
        {"Trigger Burst", "Keep firing after trigger lock."},
        {"Hit Chance", "Minimum chance to hit before triggerbot shoots."},
        {"Anti-Recoil", "Account for recoil when trigger scanning."},
        {"Trigger Delay", "Delay shot after trigger lock."},
        {"Trigger Burst", "Keep firing after trigger lock."},
        {"Hit Chance", "Minimum chance to hit before triggerbot shoots."},
        {"Anti-Recoil", "Account for recoil when trigger scanning."},
        {"Trigger Delay", "Delay shot after trigger lock."},
        {"Trigger Burst", "Keep firing after trigger lock."},
        {"Hit Chance", "Minimum chance to hit before triggerbot shoots."},
        {"Anti-Recoil", "Account for recoil when trigger scanning."},
        {"Trigger Delay", "Delay shot after trigger lock."},
        {"Trigger Burst", "Keep firing after trigger lock."},
        {"Hit Chance", "Minimum chance to hit before triggerbot shoots."},
        {"Anti-Recoil", "Account for recoil when trigger scanning."},
        {"Trigger Delay", "Delay shot after trigger lock."},
        {"Trigger Burst", "Keep firing after trigger lock."},
        {"Hit Chance", "Minimum chance to hit before triggerbot shoots."},
        {"Anti-Recoil", "Account for recoil when trigger scanning."},
        {"Trigger Delay", "Delay shot after trigger lock."},
        {"Trigger Burst", "Keep firing after trigger lock."},
        {"Hit Chance", "Minimum chance to hit before triggerbot shoots."},
        {"Anti-Recoil", "Account for recoil when trigger scanning."},
        {"Trigger Delay", "Delay shot after trigger lock."},
        {"Trigger Burst", "Keep firing after trigger lock."},
        {"Hit Chance", "Minimum chance to hit before triggerbot shoots."},
        {"Anti-Recoil", "Account for recoil when trigger scanning."},
        {"Trigger Delay", "Delay shot after trigger lock."},
        {"Trigger Burst", "Keep firing after trigger lock."},
        {"Hit Chance", "Minimum chance to hit before triggerbot shoots."},
        {"Anti-Recoil", "Account for recoil when trigger scanning."},
        {"Trigger Delay", "Delay shot after trigger lock."},
        {"Trigger Burst", "Keep firing after trigger lock."},
        {"Hit Chance", "Minimum chance to hit before triggerbot shoots."},
        {"Anti-Recoil", "Account for recoil when trigger scanning."},
        {"Trigger Delay", "Delay shot after trigger lock."},
        {"Trigger Burst", "Keep firing after trigger lock."},
        {"Hit Chance", "Minimum chance to hit before triggerbot shoots."},
        {"Anti-Recoil", "Account for recoil when trigger scanning."},
        {"Smooth Factor", "Smooth out aimbot movement."},
        {"Smooth Method", "Method to use for smooth movement."},
        {"Randomize Factor", "Randomize aimbot target position."},
        {"Curve Factor", "How non-linear the movement will be."},
        {"Smooth Factor", "Smooth out aimbot movement."},
        {"Smooth Method", "Method to use for smooth movement."},
        {"Randomize Factor", "Randomize aimbot target position."},
        {"Curve Factor", "How non-linear the movement will be."},
        {"Smooth Factor", "Smooth out aimbot movement."},
        {"Smooth Method", "Method to use for smooth movement."},
        {"Randomize Factor", "Randomize aimbot target position."},
        {"Curve Factor", "How non-linear the movement will be."},
        {"Smooth Factor", "Smooth out aimbot movement."},
        {"Smooth Method", "Method to use for smooth movement."},
        {"Randomize Factor", "Randomize aimbot target position."},
        {"Curve Factor", "How non-linear the movement will be."},
        {"Smooth Factor", "Smooth out aimbot movement."},
        {"Smooth Method", "Method to use for smooth movement."},
        {"Randomize Factor", "Randomize aimbot target position."},
        {"Curve Factor", "How non-linear the movement will be."},
        {"Smooth Factor", "Smooth out aimbot movement."},
        {"Smooth Method", "Method to use for smooth movement."},
        {"Randomize Factor", "Randomize aimbot target position."},
        {"Curve Factor", "How non-linear the movement will be."},
        {"Smooth Factor", "Smooth out aimbot movement."},
        {"Smooth Method", "Method to use for smooth movement."},
        {"Randomize Factor", "Randomize aimbot target position."},
        {"Curve Factor", "How non-linear the movement will be."},
        {"Smooth Factor", "Smooth out aimbot movement."},
        {"Smooth Method", "Method to use for smooth movement."},
        {"Randomize Factor", "Randomize aimbot target position."},
        {"Curve Factor", "How non-linear the movement will be."},
        {"Smooth Factor", "Smooth out aimbot movement."},
        {"Smooth Method", "Method to use for smooth movement."},
        {"Randomize Factor", "Randomize aimbot target position."},
        {"Curve Factor", "How non-linear the movement will be."},
        {"Smooth Factor", "Smooth out aimbot movement."},
        {"Smooth Method", "Method to use for smooth movement."},
        {"Randomize Factor", "Randomize aimbot target position."},
        {"Curve Factor", "How non-linear the movement will be."},
        {"Smooth Factor", "Smooth out aimbot movement."},
        {"Smooth Method", "Method to use for smooth movement."},
        {"Randomize Factor", "Randomize aimbot target position."},
        {"Curve Factor", "How non-linear the movement will be."},
        {"Auto Wall", "Fire through penetrable walls."},
        {"Through Smoke", "Fire through smoke."},
        {"Auto Wall", "Fire through penetrable walls."},
        {"Through Smoke", "Fire through smoke."},
        {"Auto Wall", "Fire through penetrable walls."},
        {"Through Smoke", "Fire through smoke."},
        {"Auto Wall", "Fire through penetrable walls."},
        {"Through Smoke", "Fire through smoke."},
        {"Auto Wall", "Fire through penetrable walls."},
        {"Through Smoke", "Fire through smoke."},
        {"Auto Wall", "Fire through penetrable walls."},
        {"Through Smoke", "Fire through smoke."},
        {"Auto Wall", "Fire through penetrable walls."},
        {"Through Smoke", "Fire through smoke."},
        {"Auto Wall", "Fire through penetrable walls."},
        {"Through Smoke", "Fire through smoke."},
        {"Auto Wall", "Fire through penetrable walls."},
        {"Through Smoke", "Fire through smoke."},
        {"Auto Wall", "Fire through penetrable walls."},
        {"Through Smoke", "Fire through smoke."},
        {"Auto Wall", "Fire through penetrable walls."},
        {"Through Smoke", "Fire through smoke."},
        {"Recoil Control System", "Smoothly counter weapon recoil."},
        {"Standalone Recoil Control", "Enable RCS while aiming freely."},
        {"Horizontal Recoil", "How much of horizontal recoil will be countered."},
        {"Vertical Recoil", "How much of vertical recoil will be countered."},
        {"Recoil Control System", "Smoothly counter weapon recoil."},
        {"Standalone Recoil Control", "Enable RCS while aiming freely."},
        {"Horizontal Recoil", "How much of horizontal recoil will be countered."},
        {"Vertical Recoil", "How much of vertical recoil will be countered."},
        {"Recoil Control System", "Smoothly counter weapon recoil."},
        {"Standalone Recoil Control", "Enable RCS while aiming freely."},
        {"Horizontal Recoil", "How much of horizontal recoil will be countered."},
        {"Vertical Recoil", "How much of vertical recoil will be countered."},
        {"Recoil Control System", "Smoothly counter weapon recoil."},
        {"Standalone Recoil Control", "Enable RCS while aiming freely."},
        {"Horizontal Recoil", "How much of horizontal recoil will be countered."},
        {"Vertical Recoil", "How much of vertical recoil will be countered."},
        {"Recoil Control System", "Smoothly counter weapon recoil."},
        {"Standalone Recoil Control", "Enable RCS while aiming freely."},
        {"Horizontal Recoil", "How much of horizontal recoil will be countered."},
        {"Vertical Recoil", "How much of vertical recoil will be countered."},
        {"Recoil Control System", "Smoothly counter weapon recoil."},
        {"Standalone Recoil Control", "Enable RCS while aiming freely."},
        {"Horizontal Recoil", "How much of horizontal recoil will be countered."},
        {"Vertical Recoil", "How much of vertical recoil will be countered."},
        {"Recoil Control System", "Smoothly counter weapon recoil."},
        {"Standalone Recoil Control", "Enable RCS while aiming freely."},
        {"Horizontal Recoil", "How much of horizontal recoil will be countered."},
        {"Vertical Recoil", "How much of vertical recoil will be countered."},
        {"Recoil Control System", "Smoothly counter weapon recoil."},
        {"Standalone Recoil Control", "Enable RCS while aiming freely."},
        {"Horizontal Recoil", "How much of horizontal recoil will be countered."},
        {"Vertical Recoil", "How much of vertical recoil will be countered."},
        {"Recoil Control System", "Smoothly counter weapon recoil."},
        {"Standalone Recoil Control", "Enable RCS while aiming freely."},
        {"Horizontal Recoil", "How much of horizontal recoil will be countered."},
        {"Vertical Recoil", "How much of vertical recoil will be countered."},
        {"Recoil Control System", "Smoothly counter weapon recoil."},
        {"Standalone Recoil Control", "Enable RCS while aiming freely."},
        {"Horizontal Recoil", "How much of horizontal recoil will be countered."},
        {"Vertical Recoil", "How much of vertical recoil will be countered."},
        {"Recoil Control System", "Smoothly counter weapon recoil."},
        {"Standalone Recoil Control", "Enable RCS while aiming freely."},
        {"Horizontal Recoil", "How much of horizontal recoil will be countered."},
        {"Vertical Recoil", "How much of vertical recoil will be countered."},
        {"Minimum FOV Range", "Minimum field of view for aim lock."},
        {"Maximum FOV Range", "Maximum field of view for aim lock."},
        {"Target Switch Delay", "Time aimbot will wait before switching target."},
        {"First Shot Delay", "Time till aimbot fires first shot."},
        {"Minimum FOV Range", "Minimum field of view for aim lock."},
        {"Maximum FOV Range", "Maximum field of view for aim lock."},
        {"Target Switch Delay", "Time aimbot will wait before switching target."},
        {"First Shot Delay", "Time till aimbot fires first shot."},
        {"Minimum FOV Range", "Minimum field of view for aim lock."},
        {"Maximum FOV Range", "Maximum field of view for aim lock."},
        {"Target Switch Delay", "Time aimbot will wait before switching target."},
        {"First Shot Delay", "Time till aimbot fires first shot."},
        {"Minimum FOV Range", "Minimum field of view for aim lock."},
        {"Maximum FOV Range", "Maximum field of view for aim lock."},
        {"Target Switch Delay", "Time aimbot will wait before switching target."},
        {"First Shot Delay", "Time till aimbot fires first shot."},
        {"Minimum FOV Range", "Minimum field of view for aim lock."},
        {"Maximum FOV Range", "Maximum field of view for aim lock."},
        {"Target Switch Delay", "Time aimbot will wait before switching target."},
        {"First Shot Delay", "Time till aimbot fires first shot."},
        {"Minimum FOV Range", "Minimum field of view for aim lock."},
        {"Maximum FOV Range", "Maximum field of view for aim lock."},
        {"Target Switch Delay", "Time aimbot will wait before switching target."},
        {"First Shot Delay", "Time till aimbot fires first shot."},
        {"Minimum FOV Range", "Minimum field of view for aim lock."},
        {"Maximum FOV Range", "Maximum field of view for aim lock."},
        {"Target Switch Delay", "Time aimbot will wait before switching target."},
        {"First Shot Delay", "Time till aimbot fires first shot."},
        {"Minimum FOV Range", "Minimum field of view for aim lock."},
        {"Maximum FOV Range", "Maximum field of view for aim lock."},
        {"Target Switch Delay", "Time aimbot will wait before switching target."},
        {"First Shot Delay", "Time till aimbot fires first shot."},
        {"Minimum FOV Range", "Minimum field of view for aim lock."},
        {"Maximum FOV Range", "Maximum field of view for aim lock."},
        {"Target Switch Delay", "Time aimbot will wait before switching target."},
        {"First Shot Delay", "Time till aimbot fires first shot."},
        {"Minimum FOV Range", "Minimum field of view for aim lock."},
        {"Maximum FOV Range", "Maximum field of view for aim lock."},
        {"Target Switch Delay", "Time aimbot will wait before switching target."},
        {"First Shot Delay", "Time till aimbot fires first shot."},
        {"Minimum FOV Range", "Minimum field of view for aim lock."},
        {"Maximum FOV Range", "Maximum field of view for aim lock."},
        {"Target Switch Delay", "Time aimbot will wait before switching target."},
        {"First Shot Delay", "Time till aimbot fires first shot."},
        {"Hit Chance", "Minimum chance to hit before aimbot shoots."},
        {"Min Damage", "Minimum damage required after wall penetration."},
        {"Anti-Recoil", "Counter weapon recoil for higher accuracy."},
        {"Double Fire", {"Off", "Defensive", "Offensive", "Shoot two bullets at once."}},
        {"Double Fire Indicator", "Show the Double Fire indicator."},
        {"Double Fire Hit Chance", "Minimum chance to hit for second shot."},
        {"Double Fire Fake Lag", "Maximum number of fake lag cmds with Double Fire."},
        {"Double Fire Fake Lag Conditions", "Configure fakelag options."},
        {"Hit Chance", "Minimum chance to hit before aimbot shoots."},
        {"Min Damage", "Minimum damage required after wall penetration."},
        {"Anti-Recoil", "Counter weapon recoil for higher accuracy."},
        {"Hit Chance", "Minimum chance to hit before aimbot shoots."},
        {"Min Damage", "Minimum damage required after wall penetration."},
        {"Anti-Recoil", "Counter weapon recoil for higher accuracy."},
        {"Double Fire", {"Off", "Defensive", "Offensive", "Shoot two bullets at once."}},
        {"Double Fire Indicator", "Show the Double Fire indicator."},
        {"Double Fire Hit Chance", "Minimum chance to hit for second shot."},
        {"Double Fire Fake Lag", "Maximum number of fake lag cmds with Double Fire."},
        {"Double Fire Fake Lag Conditions", "Configure fakelag options."},
        {"Hit Chance", "Minimum chance to hit before aimbot shoots."},
        {"Min Damage", "Minimum damage required after wall penetration."},
        {"Anti-Recoil", "Counter weapon recoil for higher accuracy."},
        {"Double Fire", {"Off", "Defensive", "Offensive", "Shoot two bullets at once."}},
        {"Double Fire Indicator", "Show the Double Fire indicator."},
        {"Double Fire Hit Chance", "Minimum chance to hit for second shot."},
        {"Double Fire Fake Lag", "Maximum number of fake lag cmds with Double Fire."},
        {"Double Fire Fake Lag Conditions", "Configure fakelag options."},
        {"Hit Chance", "Minimum chance to hit before aimbot shoots."},
        {"Min Damage", "Minimum damage required after wall penetration."},
        {"Anti-Recoil", "Counter weapon recoil for higher accuracy."},
        {"Double Fire", {"Off", "Defensive", "Offensive", "Shoot two bullets at once."}},
        {"Double Fire Indicator", "Show the Double Fire indicator."},
        {"Double Fire Hit Chance", "Minimum chance to hit for second shot."},
        {"Double Fire Fake Lag", "Maximum number of fake lag cmds with Double Fire."},
        {"Double Fire Fake Lag Conditions", "Configure fakelag options."},
        {"Hit Chance", "Minimum chance to hit before aimbot shoots."},
        {"Min Damage", "Minimum damage required after wall penetration."},
        {"Anti-Recoil", "Counter weapon recoil for higher accuracy."},
        {"Double Fire", {"Off", "Defensive", "Offensive", "Shoot two bullets at once."}},
        {"Double Fire Indicator", "Show the Double Fire indicator."},
        {"Double Fire Hit Chance", "Minimum chance to hit for second shot."},
        {"Double Fire Fake Lag", "Maximum number of fake lag cmds with Double Fire."},
        {"Double Fire Fake Lag Conditions", "Configure fakelag options."},
        {"Hit Chance", "Minimum chance to hit before aimbot shoots."},
        {"Min Damage", "Minimum damage required after wall penetration."},
        {"Anti-Recoil", "Counter weapon recoil for higher accuracy."},
        {"Double Fire", {"Off", "Defensive", "Offensive", "Shoot two bullets at once."}},
        {"Double Fire Indicator", "Show the Double Fire indicator."},
        {"Double Fire Hit Chance", "Minimum chance to hit for second shot."},
        {"Double Fire Fake Lag", "Maximum number of fake lag cmds with Double Fire."},
        {"Double Fire Fake Lag Conditions", "Configure fakelag options."},
        {"Hit Chance", "Minimum chance to hit before aimbot shoots."},
        {"Min Damage", "Minimum damage required after wall penetration."},
        {"Anti-Recoil", "Counter weapon recoil for higher accuracy."},
        {"Double Fire", {"Off", "Defensive", "Offensive", "Shoot two bullets at once."}},
        {"Double Fire Indicator", "Show the Double Fire indicator."},
        {"Double Fire Fake Lag", "Maximum number of fake lag cmds with Double Fire."},
        {"Double Fire Fake Lag Conditions", "Configure fakelag options."},
        {"Hit Chance", "Minimum chance to hit before aimbot shoots."},
        {"Min Damage", "Minimum damage required after wall penetration."},
        {"Anti-Recoil", "Counter weapon recoil for higher accuracy."},
        {"Double Fire", {"Off", "Defensive", "Offensive", "Shoot two bullets at once."}},
        {"Double Fire Indicator", "Show the Double Fire indicator."},
        {"Double Fire Hit Chance", "Minimum chance to hit for second shot."},
        {"Double Fire Fake Lag", "Maximum number of fake lag cmds with Double Fire."},
        {"Double Fire Fake Lag Conditions", "Configure fakelag options."},
        {"Hit Chance", "Minimum chance to hit before aimbot shoots."},
        {"Min Damage", "Minimum damage required after wall penetration."},
        {"Anti-Recoil", "Counter weapon recoil for higher accuracy."},
        {"Double Fire", {"Off", "Defensive", "Offensive", "Shoot two bullets at once."}},
        {"Double Fire Indicator", "Show the Double Fire indicator."},
        {"Double Fire Fake Lag", "Maximum number of fake lag cmds with Double Fire."},
        {"Double Fire Fake Lag Conditions", "Configure fakelag options."},
        {"Hit Chance", "Minimum chance to hit before aimbot shoots."},
        {"Min Damage", "Minimum damage required after wall penetration."},
        {"Anti-Recoil", "Counter weapon recoil for higher accuracy."},
        {"Double Fire", {"Off", "Defensive", "Offensive", "Shoot two bullets at once."}},
        {"Double Fire Indicator", "Show the Double Fire indicator."},
        {"Double Fire Hit Chance", "Minimum chance to hit for second shot."},
        {"Double Fire Fake Lag", "Maximum number of fake lag cmds with Double Fire."},
        {"Double Fire Fake Lag Conditions", "Configure fakelag options."},
        {"Double Fire", {"Off", "Defensive", "Offensive", "Shoot two bullets at once."}},
        {"Double Fire Indicator", "Show the Double Fire indicator."},
        {"Double Fire Fake Lag", "Maximum number of fake lag cmds with Double Fire."},
        {"Double Fire Fake Lag Conditions", "Configure fakelag options."},
        {"Auto Stop", "Counter strafe when shooting to lower inaccuracy."},
        {"Auto Stop Options"},
        {"Auto Stop", "Counter strafe when shooting to lower inaccuracy."},
        {"Auto Stop Options"},
        {"Auto Stop", "Counter strafe when shooting to lower inaccuracy."},
        {"Auto Stop Options"},
        {"Auto Stop", "Counter strafe when shooting to lower inaccuracy."},
        {"Auto Stop Options"},
        {"Auto Stop", "Counter strafe when shooting to lower inaccuracy."},
        {"Auto Stop Options"},
        {"Auto Stop", "Counter strafe when shooting to lower inaccuracy."},
        {"Auto Stop Options"},
        {"Auto Stop", "Counter strafe when shooting to lower inaccuracy."},
        {"Auto Stop Options"},
        {"Auto Stop", "Counter strafe when shooting to lower inaccuracy."},
        {"Auto Stop Options"},
        {"Auto Stop", "Counter strafe when shooting to lower inaccuracy."},
        {"Auto Stop Options"},
        {"Auto Stop", "Counter strafe when shooting to lower inaccuracy."},
        {"Auto Stop Options"},
        {"Auto Stop", "Counter strafe when shooting to lower inaccuracy."},
        {"Auto Stop Options"},
        {"Precise Hitscan", "Enable additional checks when selecting hit points."},
        {"Predictive", "Wait for higher damage spot when peeking."},
        {"Precise Hitscan", "Enable additional checks when selecting hit points."},
        {"Predictive", "Wait for higher damage spot when peeking."},
        {"Precise Hitscan", "Enable additional checks when selecting hit points."},
        {"Predictive", "Wait for higher damage spot when peeking."},
        {"Precise Hitscan", "Enable additional checks when selecting hit points."},
        {"Predictive", "Wait for higher damage spot when peeking."},
        {"Precise Hitscan", "Enable additional checks when selecting hit points."},
        {"Predictive", "Wait for higher damage spot when peeking."},
        {"Precise Hitscan", "Enable additional checks when selecting hit points."},
        {"Predictive", "Wait for higher damage spot when peeking."},
        {"Precise Hitscan", "Enable additional checks when selecting hit points."},
        {"Predictive", "Wait for higher damage spot when peeking."},
        {"Precise Hitscan", "Enable additional checks when selecting hit points."},
        {"Predictive", "Wait for higher damage spot when peeking."},
        {"Precise Hitscan", "Enable additional checks when selecting hit points."},
        {"Predictive", "Wait for higher damage spot when peeking."},
        {"Precise Hitscan", "Enable additional checks when selecting hit points."},
        {"Predictive", "Wait for higher damage spot when peeking."},
        {"Precise Hitscan", "Enable additional checks when selecting hit points."},
        {"Predictive", "Wait for higher damage spot when peeking."},
        {"Auto Wall", "Shoot through penetrable walls."},
        {"Bodyaim", "Configure bodyaim prioritization."},
        {"Prioritize Safe Point", "Prioritize overlapped hitbox points."},
        {"Force Safe Point", "Force waiting for overlapped hitbox points."},
        {"Auto Wall", "Shoot through penetrable walls."},
        {"Bodyaim", "Configure bodyaim prioritization."},
        {"Prioritize Safe Point", "Prioritize overlapped hitbox points."},
        {"Force Safe Point", "Force waiting for overlapped hitbox points."},
        {"Auto Wall", "Shoot through penetrable walls."},
        {"Bodyaim", "Configure bodyaim prioritization."},
        {"Prioritize Safe Point", "Prioritize overlapped hitbox points."},
        {"Force Safe Point", "Force waiting for overlapped hitbox points."},
        {"Auto Wall", "Shoot through penetrable walls."},
        {"Bodyaim", "Configure bodyaim prioritization."},
        {"Prioritize Safe Point", "Prioritize overlapped hitbox points."},
        {"Force Safe Point", "Force waiting for overlapped hitbox points."},
        {"Auto Wall", "Shoot through penetrable walls."},
        {"Bodyaim", "Configure bodyaim prioritization."},
        {"Prioritize Safe Point", "Prioritize overlapped hitbox points."},
        {"Force Safe Point", "Force waiting for overlapped hitbox points."},
        {"Auto Wall", "Shoot through penetrable walls."},
        {"Bodyaim", "Configure bodyaim prioritization."},
        {"Prioritize Safe Point", "Prioritize overlapped hitbox points."},
        {"Force Safe Point", "Force waiting for overlapped hitbox points."},
        {"Auto Wall", "Shoot through penetrable walls."},
        {"Bodyaim", "Configure bodyaim prioritization."},
        {"Prioritize Safe Point", "Prioritize overlapped hitbox points."},
        {"Force Safe Point", "Force waiting for overlapped hitbox points."},
        {"Auto Wall", "Shoot through penetrable walls."},
        {"Bodyaim", "Configure bodyaim prioritization."},
        {"Prioritize Safe Point", "Prioritize overlapped hitbox points."},
        {"Force Safe Point", "Force waiting for overlapped hitbox points."},
        {"Auto Wall", "Shoot through penetrable walls."},
        {"Bodyaim", "Configure bodyaim prioritization."},
        {"Prioritize Safe Point", "Prioritize overlapped hitbox points."},
        {"Force Safe Point", "Force waiting for overlapped hitbox points."},
        {"Auto Wall", "Shoot through penetrable walls."},
        {"Bodyaim", "Configure bodyaim prioritization."},
        {"Prioritize Safe Point", "Prioritize overlapped hitbox points."},
        {"Force Safe Point", "Force waiting for overlapped hitbox points."},
        {"Auto Wall", "Shoot through penetrable walls."},
        {"Bodyaim", "Configure bodyaim prioritization."},
        {"Prioritize Safe Point", "Prioritize overlapped hitbox points."},
        {"Force Safe Point", "Force waiting for overlapped hitbox points."},
        {"Rotation Offset"},
        {"LBY Offset"},
        {"Spinbot Speed"},
        {"Rotation Offset"},
        {"LBY Offset"},
        {"Spinbot Speed"},
        {"Rotation Offset"},
        {"LBY Offset"},
        {"Spinbot Speed"},
        {"On Use", "Disable anti-aim when pressing the Use key."},
        {"On Knife", "Disable anti-aim when holding knife."},
        {"On Grenade", "Disable anti-aim when holding a grenade."},
        {"During Freeze Time", "Disable anti-aim at the beginning of a round."},
        {"At Edges", "Apply left/right direction based on nearby walls."},
        {"At Targets", "Always face nearby enemies direction."},
        {"Bar"},
        {"Number"},
        {"Defusing"},
        {"Planting"},
        {"Scoped"},
        {"Reloading"},
        {"Flashed"},
        {"Has Defuser"},
        {"Has C4"},
        {"Ping"},
        {"Bar"},
        {"Number"},
        {"Defusing"},
        {"Planting"},
        {"Scoped"},
        {"Reloading"},
        {"Flashed"},
        {"Has Defuser"},
        {"Has C4"},
        {"Ping"},
        {"Name"},
        {"Icon"},
        {"Detonate Timer"},
        {"Damage"},
        {"Grid"},
        {"Sound"},
        {"Marker"},
        {"Local"},
        {"Friendly"},
        {"Enemy"},
        {"Local"},
        {"Friendly"},
        {"Enemy"},
        {"Local"},
        {"Friendly"},
        {"Enemy"},
        {"Local"},
        {"Friendly"},
        {"Enemy"},
        {"Search", "Type the sticker to search."},
        {"Set"},
        {"Reset"},
        {"Search", "Type the sticker to search."},
        {"Set"},
        {"Reset"},
        {"Search", "Type the sticker to search."},
        {"Set"},
        {"Reset"},
        {"Search", "Type the sticker to search."},
        {"Set"},
        {"Reset"},
        {"Search", "Type the sticker to search."},
        {"Set"},
        {"Reset"},
        {"No Flash"},
        {"No Smoke"},
        {"No Recoil"},
        {"No Scope"},
        {"No Scope Overlay"},
        {"No Scope Dirt"},
        {"No Sky"},
        {"No Fog"},
        {"No Post Processing"},
        {"No Render For Teammates"},
        {"No Render For Enemies"},
        {"No Render For Weapons"},
        {"No Render For Ragdolls"},
        {"Disable Far Models"},
        {"Local"},
        {"Friendly"},
        {"Enemy"},
        {"Peek", "Lag your model behind wall when peeking."},
        {"While Standing"},
        {"While Moving"},
        {"While In Air"}
    },
    {
        {"While Standing"},
        {"While Moving"},
        {"While In Air"},
        {"While Standing"},
        {"While Moving"},
        {"While In Air"},
        {"While Standing"},
        {"While Moving"},
        {"While In Air"},
        {"While Standing"},
        {"While Moving"},
        {"While In Air"},
        {"While Standing"},
        {"While Moving"},
        {"While In Air"},
        {"While Standing"},
        {"While Moving"},
        {"While In Air"},
        {"While Standing"},
        {"While Moving"},
        {"While In Air"},
        {"While Standing"},
        {"While Moving"},
        {"While In Air"},
        {"While Standing"},
        {"While Moving"},
        {"While In Air"},
        {"While Standing"},
        {"While Moving"},
        {"While In Air"},
        {"While Standing"},
        {"While Moving"},
        {"While In Air"},
        {"Between Shots", "Enable continuous auto stop between shots."},
        {"Early", "Stop earlier for higher initial accuracy."},
        {"Slow Walk", "Allow slow walk movement during auto stop."},
        {"Duck", "Duck during auto stop to further increase accuracy."},
        {"In Molotov", "Allow auto stop within a molotov radius."},
        {"In Air", "Allow auto stop while airbourne."},
        {"Between Shots", "Enable continuous auto stop between shots."},
        {"Early", "Stop earlier for higher initial accuracy."},
        {"Slow Walk", "Allow slow walk movement during auto stop."},
        {"Duck", "Duck during auto stop to further increase accuracy."},
        {"In Molotov", "Allow auto stop within a molotov radius."},
        {"In Air", "Allow auto stop while airbourne."},
        {"Between Shots", "Enable continuous auto stop between shots."},
        {"Early", "Stop earlier for higher initial accuracy."},
        {"Slow Walk", "Allow slow walk movement during auto stop."},
        {"Duck", "Duck during auto stop to further increase accuracy."},
        {"In Molotov", "Allow auto stop within a molotov radius."},
        {"In Air", "Allow auto stop while airbourne."},
        {"Between Shots", "Enable continuous auto stop between shots."},
        {"Early", "Stop earlier for higher initial accuracy."},
        {"Slow Walk", "Allow slow walk movement during auto stop."},
        {"Duck", "Duck during auto stop to further increase accuracy."},
        {"In Molotov", "Allow auto stop within a molotov radius."},
        {"In Air", "Allow auto stop while airbourne."},
        {"Between Shots", "Enable continuous auto stop between shots."},
        {"Early", "Stop earlier for higher initial accuracy."},
        {"Slow Walk", "Allow slow walk movement during auto stop."},
        {"Duck", "Duck during auto stop to further increase accuracy."},
        {"In Molotov", "Allow auto stop within a molotov radius."},
        {"In Air", "Allow auto stop while airbourne."},
        {"Between Shots", "Enable continuous auto stop between shots."},
        {"Early", "Stop earlier for higher initial accuracy."},
        {"Slow Walk", "Allow slow walk movement during auto stop."},
        {"Duck", "Duck during auto stop to further increase accuracy."},
        {"In Molotov", "Allow auto stop within a molotov radius."},
        {"In Air", "Allow auto stop while airbourne."},
        {"Between Shots", "Enable continuous auto stop between shots."},
        {"Early", "Stop earlier for higher initial accuracy."},
        {"Slow Walk", "Allow slow walk movement during auto stop."},
        {"Duck", "Duck during auto stop to further increase accuracy."},
        {"In Molotov", "Allow auto stop within a molotov radius."},
        {"In Air", "Allow auto stop while airbourne."},
        {"Between Shots", "Enable continuous auto stop between shots."},
        {"Early", "Stop earlier for higher initial accuracy."},
        {"Slow Walk", "Allow slow walk movement during auto stop."},
        {"Duck", "Duck during auto stop to further increase accuracy."},
        {"In Molotov", "Allow auto stop within a molotov radius."},
        {"In Air", "Allow auto stop while airbourne."},
        {"Between Shots", "Enable continuous auto stop between shots."},
        {"Early", "Stop earlier for higher initial accuracy."},
        {"Slow Walk", "Allow slow walk movement during auto stop."},
        {"Duck", "Duck during auto stop to further increase accuracy."},
        {"In Molotov", "Allow auto stop within a molotov radius."},
        {"In Air", "Allow auto stop while airbourne."},
        {"Between Shots", "Enable continuous auto stop between shots."},
        {"Early", "Stop earlier for higher initial accuracy."},
        {"Slow Walk", "Allow slow walk movement during auto stop."},
        {"Duck", "Duck during auto stop to further increase accuracy."},
        {"In Molotov", "Allow auto stop within a molotov radius."},
        {"In Air", "Allow auto stop while airbourne."},
        {"Between Shots", "Enable continuous auto stop between shots."},
        {"Early", "Stop earlier for higher initial accuracy."},
        {"Slow Walk", "Allow slow walk movement during auto stop."},
        {"Duck", "Duck during auto stop to further increase accuracy."},
        {"In Molotov", "Allow auto stop within a molotov radius."},
        {"In Air", "Allow auto stop while airbourne."},
        {"Force", "Always prioritize bodyaim."},
        {"Lethal", "Bodyaim when shot will be lethal."},
        {"On Shot", "Bodyaim when enemy is shooting."},
        {"No Head Safepoint", "Bodyaim when head hitboxes do not overlap."},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Force", "Always prioritize bodyaim."},
        {"Lethal", "Bodyaim when shot will be lethal."},
        {"On Shot", "Bodyaim when enemy is shooting."},
        {"No Head Safepoint", "Bodyaim when head hitboxes do not overlap."},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Force", "Always prioritize bodyaim."},
        {"Lethal", "Bodyaim when shot will be lethal."},
        {"On Shot", "Bodyaim when enemy is shooting."},
        {"No Head Safepoint", "Bodyaim when head hitboxes do not overlap."},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Force", "Always prioritize bodyaim."},
        {"Lethal", "Bodyaim when shot will be lethal."},
        {"On Shot", "Bodyaim when enemy is shooting."},
        {"No Head Safepoint", "Bodyaim when head hitboxes do not overlap."},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Force", "Always prioritize bodyaim."},
        {"Lethal", "Bodyaim when shot will be lethal."},
        {"On Shot", "Bodyaim when enemy is shooting."},
        {"No Head Safepoint", "Bodyaim when head hitboxes do not overlap."},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Force", "Always prioritize bodyaim."},
        {"Lethal", "Bodyaim when shot will be lethal."},
        {"On Shot", "Bodyaim when enemy is shooting."},
        {"No Head Safepoint", "Bodyaim when head hitboxes do not overlap."},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Force", "Always prioritize bodyaim."},
        {"Lethal", "Bodyaim when shot will be lethal."},
        {"On Shot", "Bodyaim when enemy is shooting."},
        {"No Head Safepoint", "Bodyaim when head hitboxes do not overlap."},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Force", "Always prioritize bodyaim."},
        {"Lethal", "Bodyaim when shot will be lethal."},
        {"On Shot", "Bodyaim when enemy is shooting."},
        {"No Head Safepoint", "Bodyaim when head hitboxes do not overlap."},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Force", "Always prioritize bodyaim."},
        {"Lethal", "Bodyaim when shot will be lethal."},
        {"On Shot", "Bodyaim when enemy is shooting."},
        {"No Head Safepoint", "Bodyaim when head hitboxes do not overlap."},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Force", "Always prioritize bodyaim."},
        {"Lethal", "Bodyaim when shot will be lethal."},
        {"On Shot", "Bodyaim when enemy is shooting."},
        {"No Head Safepoint", "Bodyaim when head hitboxes do not overlap."},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Force", "Always prioritize bodyaim."},
        {"Lethal", "Bodyaim when shot will be lethal."},
        {"On Shot", "Bodyaim when enemy is shooting."},
        {"No Head Safepoint", "Bodyaim when head hitboxes do not overlap."},
        {"Head"},
        {"Body"},
        {"Limbs"},
        {"Head"},
        {"Body"},
        {"Limbs"}
    }
}
